#!/bin/sh /etc/rc.common

START=49

start() {
	logger -t gpg "Generating GPG key..."
	/usr/bin/gpg --batch --gen-key /etc/domino/gpg_gen_key_batch
	logger -t gpg "GPG key generated. Exporting key as ascii text file..."
	rm -f /etc/domino/domino_gpg.asc
	/usr/bin/gpg --no-default-keyring --secret-keyring /etc/domino/domino_gpg.sec --keyring /etc/domino/domino_gpg.pub --export --armor --output /etc/domino/domino_gpg.asc
	logger -t gpg "GPG key exported"
}

